# Generated by Django 6.0.2 on 2026-03-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(default=0),
        ),
    ]
