# Generated by Django 6.0.2 on 2026-02-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidateprofile_recruiterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RecruiterProfile',
        ),
    ]
